# .streamlit/config.toml

[theme]
base = "light"
primaryColor = "#003366"
backgroundColor = "#FFFFFF"           # Main content area: true white
secondaryBackgroundColor = "#F5F7FA"  # Sidebar: very light gray-blue (for soft contrast)
textColor = "#343A40"
font = "sans serif"