# .streamlit/config.toml

# .streamlit/config.toml

[theme]
base="light"  # Ensures we're starting from the light theme baseline
primaryColor="#4A90E2"  # A nice, professional blue for buttons and accents
backgroundColor="#FFFFFF"  # Pure white for main background
secondaryBackgroundColor="#F0F2F6"  # Subtle grey for sidebar and widgets
textColor="#333333"  # Soft black for easier reading
font="sans serif"  # Clean and modern font for UI

# Optional aesthetic tweaks
# borderRadius = 0.5
# sidebarWidth = "280px"